### PR TITLE
Add appeared in smsl.pldb

### PR DESCRIPTION
**Pull request by stavares843**
info from: http://xml.coverpages.org/smslFerris0.html

### CODE REVIEW

**Comment by stavares843** [comment]
https://github.com/breck7/pldb/issues/110

**Comment by breck7** [comment]
Feel free to commit directly to main @stavares843 !

**Comment by stavares843** [comment]
thanks! 🔨

**Comment by celtic-coder** [comment]
> Feel free to commit directly to main @stavares843 !

👍 Good work!

**Pull request merged**
