### PR TITLE
Add databases

### PR DESCRIPTION
**Pull request by stavares843**
Adds the following databases:
- `database/things/couchbase-mobile.pldb`
- `database/things/greenplum.pldb`
- `database/things/influxdb.pldb`
- `database/things/interbase.pldb`
- `database/things/memcached.pldb`
- `database/things/teradata-aster.pldb`
- `database/things/tidb.pldb`
- `database/things/yugabytedb.pldb`

### CODE REVIEW

**Comment by breck7** [comment]
LGTM.

I would now focus on going deeper on all these databases you just added.

Add `wikipedia` for each. Then you can run the Wikipedia crawler to extract a lot of data from that.

Then add `isOpenSource`. Then add `githubRepo` for each (or `gitLabRepo`/`sourceHutRepo`/`gitRepo` if they don't use `gitHub`). Then you can run the GitHub crawler and extract a lot more data.

From there you should be able to get the `writtenIn` field.

And at that point they all would be nicely connected to programming languages, and we could answer some interesting questions such as "databases are perhaps the most important type of application. what language(s) do database developers use to write their databases?"

Another field to then add would be what query languages does each database use. For example, for Oracle it would include https://pldb.com/languages/pl-sql.html

**Comment by stavares843** [comment]
thanks, will do! 🔨

**Comment by stavares843** [comment]
is there any docs regarding running the crawlers? 🔨 i took a look but couldn't find

**Comment by breck7** [comment]
@stavares843 I'm working on the crawlers right now :)

Moved them to a separate project and will add docs. https://github.com/breck7/treecrawler

**Comment by breck7** [comment]
@stavares843 I'm working on the crawlers right now :)

Moved them to a separate project and will add docs. https://github.com/breck7/treecrawler

**Comment by breck7** [comment]
@stavares843 I'm working on the crawlers right now :)

Moved them to a separate project and will add docs. https://github.com/breck7/treecrawler

**Comment by stavares843** [comment]
awesome, thanks! 🔨

**Pull request merged**
