### PR TITLE
added search bars to multiple lists

### PR DESCRIPTION
**Pull request by mahadwaseem123**
Hi @breck7 , added search bar to multiple lists. #218 is also covered.

### CODE REVIEW

**Comment by breck7** [comment]
great work @mahadwaseem123 !

**Comment by mahadwaseem123** [comment]
Thanks a lot @breck7

**Comment by celtic-coder** [comment]
Excellent work, Mahad (@mahadwaseem123)! 👍

**Comment by mahadwaseem123** [comment]
Thanks a lot @celtic-coder

**Pull request merged**
