### PR TITLE
Update rye.pldb

### PR DESCRIPTION
**Pull request by refaktor**

### CODE REVIEW

**Comment by celtic-coder** [comment]
Hi @refaktor,

Thanks for the update!

Kind Regards,
Liam

**Comment by refaktor** [comment]
Thank you :) . I noticed a visitor to a site from pldb.pub, so I went checking it out :)

**Comment by celtic-coder** [comment]
Hi Janko (@refaktor),

I trust that PLDB will prove to be useful for you. Rye looks to be an interesting language! Since it has REBOL roots, you might like to look at Arturo (https://arturo-lang.io/) as there seems to be some overlap. 

Wishing you all the best in your endeavour!

Kind Regards,
Liam

**Comment by refaktor** [comment]
Hi Liam,

Thank you, as a language nut :), I found pldb very interesting also and I will be browsing it more, and trying to fill in more info for Rye. Arturo is interesting yes and starts from the same REBOL foundations. We both explore REBOL ideas in our own ways so it's all very interesting to me :). I do link to it and Red and some other variations in the Rye's github readme.

Thank you again, best wisher.
Janko

**Pull request merged**
