### PR TITLE
resolves issue #534 - created cognate.scroll

### PR DESCRIPTION
**Pull request by ravixalgorithm**
resolves issue #534 - new programming language Cognate added

### CODE REVIEW

**Comment by celtic-coder** [comment]
Hi @ravixalgorithm, 

There is an error in the Scroll document:

~~~
2024-07-09T18:10:35.7284042Z cognate.scroll ExtraWord 195  2    Delete word "" at cell 2 githubRepo ExtraWord at line 195 cell 2. Extra word "" in githubRepoParser.
~~~

Kind regards,
Liam

Cc: @breck7

**Comment by celtic-coder** [comment]
More context:

~~~
2024-07-09T18:10:35.7275252Z ❌ 1 errors in "/home/runner/work/pldb/pldb/concepts"
2024-07-09T18:10:35.7282018Z filename       type      line cell suggestion               path       message                                                         
2024-07-09T18:10:35.7284042Z cognate.scroll ExtraWord 195  2    Delete word "" at cell 2 githubRepo ExtraWord at line 195 cell 2. Extra word "" in githubRepoParser.
2024-07-09T18:10:35.7285170Z 
~~~

**Comment by breck7** [comment]
Just a few minor typos. Great job @ravixalgorithm ! Great job @celtic-coder !

**Comment by ravixalgorithm** [comment]
> More context:
> 
> ~~~
> 2024-07-09T18:10:35.7275252Z ❌ 1 errors in "/home/runner/work/pldb/pldb/concepts"
> 2024-07-09T18:10:35.7282018Z filename       type      line cell suggestion               path       message                                                         
> 2024-07-09T18:10:35.7284042Z cognate.scroll ExtraWord 195  2    Delete word "" at cell 2 githubRepo ExtraWord at line 195 cell 2. Extra word "" in githubRepoParser.
> 2024-07-09T18:10:35.7285170Z 
> ~~~
> 

Thanks a lot for pointing out this error

**Pull request merged**
