### PR TITLE
add annual reports

### PR DESCRIPTION
**Pull request by rkimera94**

### CODE REVIEW

**Comment by celtic-coder** [comment]
Thanks Kimera (@rkimera94)! 👍

**Comment by breck7** [comment]
Good points @rkimera94 ! Maybe we should have a `releaseNotesUrl` field, a `eventsPageUrl` and a `officialBlogUrl`

**Comment by rkimera94** [comment]
okay, good @breck7  let me check it out! And work on those different URLs

**Comment by rkimera94** [comment]
@breck7  

> Good points @rkimera94 ! Maybe we should have a `releaseNotesUrl` field, a `eventsPageUrl` and a `officialBlogUrl`

I have made some changes to the reports/ release notes, and official blogs pages. 
Introducing 4 classes 
[PR for review](https://github.com/breck7/pldb/pull/264l)

**Pull request merged**
