### PR TITLE
Update lobster.pldb

### PR DESCRIPTION
**Pull request by aardappel**

### CODE REVIEW

**Comment by breck7** [comment]
@aardappel I can't believe we don't have TreeSheets! i'm mortified ;)

**Comment by aardappel** [comment]
@breck7 Hah, not sure it classifies as a programming language, though it does contain a minimalistic one :)

**Comment by breck7** [comment]
lol.
if only there were a name for that

**Comment by breck7** [comment]
sincerely,
- idea stealer

**Pull request merged**
