### PR TITLE
add new features

### PR DESCRIPTION
**Pull request by rkimera94**

### CODE REVIEW

**Comment by breck7** [comment]
This is interesting. Nice work @rkimera94 ! I need to think about this a bit before merging in.

**Comment by rkimera94** [comment]
@breck7  do I need to make any changes or reviews on this PR?

**Comment by breck7** [comment]
No @rkimera94 this is good. I haven't merged it in yet though just because I'm currently redo-ing how we do features. I'll just leave it open for a few more days until I get that done. Sound good?

**Comment by breck7** [comment]
Im going to close this for now. I need to redo features.

**Pull request closed without merging**
