### PR TITLE
add postgres languages/applications

### PR DESCRIPTION
**Pull request by rkimera94**

### CODE REVIEW

**Comment by celtic-coder** [comment]
Hi Kimera (@rkimera94),

Both the 14.x and the 15.x builds are failing with:

`Error: Broken permalink in 'bucardo': No language "postgres" found`

I think this is because  [postgresql.pldb](https://github.com/breck7/pldb/blob/main/database/things/postgresql.pldb) exists, but not a *postgres.pldb*. This is in the `related` line for **bucardo.pldb**.

Could you check and update, as necessary?

Thanks!
Liam

**Comment by celtic-coder** [comment]
Hi Kimera (@rkimera94),

The 15.x build is failing with:

`Broken permalink in 'bucardo': No language "pgSQL" found`

Was this meant to be _pgql_, perhaps?

Kind Regards,
Liam

**Comment by rkimera94** [comment]
hi, @celtic-coder  let me check  !

**Comment by celtic-coder** [comment]
Hi Kimera (@rkimera94),

The `wikipedia https://en.wikipedia.org/wiki/Slony-I` line in _bucardo.pldb_ is generating an error. A duplicate of what is in _slony.pldb_, perhaps? A copy / paste error?

Kind Regards,
Liam

**Comment by rkimera94** [comment]
@celtic-coder  let me have review of this PR for all the changes

**Comment by celtic-coder** [comment]
Hi Kimera (@rkimera94),

There seems to be a problem with the `issues 01` line in _slony.pldb_:

````
2022-10-17T21:42:43.5194259Z Slony githubRepo issues InvalidWordError {
2022-10-17T21:42:43.5194818Z   _node: githubIssuesNode {
2022-10-17T21:42:43.5195200Z     _nodeCreationTime: 346173.681019,
2022-10-17T21:42:43.5195538Z     _parent: githubRepoNode {
2022-10-17T21:42:43.5195905Z       _nodeCreationTime: 346173.673019,
2022-10-17T21:42:43.5196271Z       _parent: [pldbNode],
2022-10-17T21:42:43.5196931Z       _line: 'githubRepo https://github.com/ssinger/slony1-engine',
2022-10-17T21:42:43.5197300Z       _children: [Array],
2022-10-17T21:42:43.5197584Z       _cachedLineNumber: 11,
2022-10-17T21:42:43.5197881Z       _words: [Array]
2022-10-17T21:42:43.5198137Z     },
2022-10-17T21:42:43.5198457Z     _line: 'issues 01',
2022-10-17T21:42:43.5198736Z     _children: [],
2022-10-17T21:42:43.5199029Z     _cachedLineNumber: 16,
2022-10-17T21:42:43.5199654Z     _words: [ 'issues', '01' ]
2022-10-17T21:42:43.5199930Z   },
````

I'm guessing that the leading zero is causing the value not to be treated as an integer.

Have patience -- we're almost there! 😄 

Kind Regards,
Liam

**Comment by rkimera94** [comment]
thanks @celtic-coder

**Comment by celtic-coder** [comment]
Well done, Kimera (@rkimera94)! ㊗️

**Pull request merged**
