### PR TITLE
Create crap.scroll

### PR DESCRIPTION
**Pull request by themanyone**
I give you crap.
For writing crap code!
Enjoy! :)

### CODE REVIEW

**Comment by celtic-coder** [comment]
Thanks, Henry! (@themanyone) 👍

**Comment by celtic-coder** [comment]
Hi Breck (@breck7), 

https://pldb.io/concepts/crap.html

is generating a 404 error. Any idea why this is happening?

Kind regards,
Liam

**Comment by celtic-coder** [comment]
The Explorer is responding with an entry in the database:

https://pldb.io/lists/explorer.html#q=Crap

**Comment by celtic-coder** [comment]
The **_crap.scroll_** file has been created on both the [main](https://github.com/breck7/pldb/blob/main/concepts/crap.scroll) and [wws](https://github.com/breck7/pldb/blob/wws/concepts/crap.scroll) branches. I've briefly checked the logs, but have not found anything out of the ordinary.

**Comment by breck7** [comment]
Fixed! Just needed the import header.

https://www.youtube.com/watch?v=-TVsdAN6vuM

**Comment by celtic-coder** [comment]
Hey Breck (@breck7),

We get a YouTube video at 4 o'clock in the morning! 👍
That was actually very helpful seeing how the command line steps work together.

Great stuff!

Thanks!
Liam

**Pull request merged**
